// Per A013/OrchestrationPanel + feedback/five-layer: contracts are the first
// thing written. Observation produces `OrchestrationObservation`; events
// consume `OrchestrationEventHandlers`; layout reads these as props.
//
// Data sources (zero new backend endpoints):
//   • GET /api/agents                            → all agents, filter id!=='default'
//   • GET /api/agents/{id}/chats                 → ChatSpec[] for a sub-agent
//   • GET /api/agents/{id}/chats/{chat_id}       → { messages, status }
//
// Sub-agent session ids are generated by QwenPaw as
// `orchestrator:to:<subagent>:<ts>:<uuid>` — one chat per delegation call.

// ─── API raw shapes ──────────────────────────────────────────────────────────

export interface ApiAgent {
  readonly id: string;
  readonly name: string;
  readonly description?: string;
  readonly workspace_dir: string;
  readonly enabled: boolean;
}

export interface ApiAgentListResponse {
  readonly agents: readonly ApiAgent[];
}

export interface ApiChatSpec {
  readonly id: string;               // chat uuid (what we fetch messages by)
  readonly session_id: string;       // e.g. "orchestrator:to:glm_research:…"
  readonly user_id?: string;
  readonly channel?: string;
  readonly created_at?: string;
  readonly status?: 'idle' | 'running';
}

export interface ApiChatHistory {
  readonly messages: readonly ApiMessage[];
  readonly status: 'idle' | 'running';
}

/** AgentScope Runtime message. `content` is a union of block types. */
export interface ApiMessage {
  readonly type: 'message' | 'reasoning' | 'plugin_call' | 'plugin_call_output' | string;
  readonly role: 'user' | 'assistant' | 'system' | 'tool';
  readonly content: readonly ApiContentBlock[];
  readonly metadata?: Record<string, unknown>;
  readonly id?: string;
  readonly status?: string;
}

export type ApiContentBlock =
  | { readonly type: 'text'; readonly text: string; readonly delta?: boolean }
  | { readonly type: 'image'; readonly image_url?: string }
  | { readonly type: 'audio'; readonly audio_url?: string; readonly data?: string }
  | { readonly type: 'video'; readonly video_url?: string }
  | { readonly type: 'file'; readonly file_url?: string; readonly file_name?: string }
  | { readonly type: 'data'; readonly data: Record<string, unknown> }
  | { readonly type: string; readonly [k: string]: unknown };

// ─── UI row shapes ───────────────────────────────────────────────────────────

export type SubAgentStatus = 'idle' | 'working' | 'error';

/** One row in the left PretextList. Only sub-agents (orchestrator filtered out). */
export interface SubAgentRow {
  readonly id: string;
  readonly name: string;
  readonly description?: string;
  readonly status: SubAgentStatus;
  readonly turnCount: number;       // # chats this agent has had
  readonly lastActivityAt: string | null;
}

/**
 * One entry in the right conversation timeline. We render the selected
 * sub-agent's full chat history as a flat list of turns. Each turn is a
 * single content block, already flattened from the message → content[N]
 * shape QwenPaw returns, so the renderer doesn't branch.
 */
export interface ConversationTurn {
  readonly id: string;                    // synthesized from msg.id + block index
  readonly agentId: string;               // 'orchestrator' for inbound delegation, sub-agent id for its own output
  readonly role: ApiMessage['role'];
  readonly kind: 'text' | 'reasoning' | 'tool_call' | 'tool_result' | 'media';
  readonly text: string;                  // rendered body (or JSON-pretty for tool args/output)
  readonly ts: string | null;
  readonly status?: string;
}

// ─── Observation (read-only view) ────────────────────────────────────────────

export interface OrchestrationObservation {
  readonly subAgents: readonly SubAgentRow[];
  readonly selectedAgentId: string | null;
  /** Chats for the selected agent — latest first. */
  readonly selectedAgentChats: readonly ApiChatSpec[];
  /** Currently-focused chat id (defaults to selectedAgentChats[0]?.id). */
  readonly selectedChatId: string | null;
  /** Turns for the selected chat, chronological (oldest first). */
  readonly conversation: readonly ConversationTurn[];
  readonly loading: boolean;
  readonly error: string | null;
}

// ─── Events (outward callbacks) ──────────────────────────────────────────────

export interface OrchestrationEventHandlers {
  readonly onSelectAgent: (id: string) => void;
  readonly onSelectChat: (chatId: string) => void;
  readonly onRefresh: () => void;
}
